version: '3.8'

services:
  database:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg-data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/quiz
      SPRING.PROFILES.ACTIVE: dev
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "80:80"
volumes:
  pg-data:
