spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/quiz'
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
logging:
  level:
    org:
      zalando:
        logbook: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"