spring:
  jackson:
    serialization:
      indent_output: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
springdoc:
  swagger-ui:
    path: /api/v1/docs
  api-docs:
    path: /api/v1/docs-json
auth:
  jwt:
    token:
      access:
        expiration: 72_000_00
        secret: 3272357538782F413F4428472B4B6250655368566B5970337336763979244226
      refresh:
        expiration: 864_000_00
logging:
  level:
    org:
      springframework:
        web:
          INFO
      hibernate:
        INFO